rhobot artifacts
cfpb/rhobot pull request #30
Opened 2016-09-19 19:40 UTC by frank0631

new command line feature. fetching of artifacts from gocd

2016-09-20 18:19 UTC, tanderegg commented on gocd/gocd.go
> +	// log.Debug("pipelineHistory JSON:", string(prettyJSON.Bytes()))
Let's leave the debug in there

2016-09-20 18:24 UTC, tanderegg commented on gocd/gocd.go
> +func History(server *Server, name string) (latestRuns map[string]int, err error) {
Let's add some more comments to better annotate what's going on (for others and our future selves)

2016-09-20 18:26 UTC, tanderegg commented on gocd/gocd_test.go
> +// //Test require a pipeline to have a history
Add in comment here briefly explaining why these are commented and what we could do to test in the future.

2016-09-20 18:29 UTC, tanderegg commented on rhobot.go
> +		Usage: "which run of the stage history",
Copy.paste error :)

2016-09-20 18:33 UTC, tanderegg commented on rhobot.go
> +				if c.String(pipelineRunFlag.GetName()) != "" {
I think this approach is preferable to the two below

2016-09-20 18:38 UTC, tanderegg commented on rhobot.go
> +		f, createErr := os.Create(artifactSavePath)
Sadly, we must catch each error sequentially.

2016-09-20 18:39 UTC, tanderegg requested changes
Great work Frank, just a few changes!

2016-09-21 14:38 UTC, frank0631 commented on gocd/gocd.go
> +	// log.Debug("pipelineHistory JSON:", string(prettyJSON.Bytes()))
added it back in 21360bb9931065514aeb581cf0c7282830c65dae, along with a refractor to limit rewritten code

2016-09-21 14:43 UTC, frank0631 commented on gocd/gocd.go
> +func History(server *Server, name string) (latestRuns map[string]int, err error) {
better comments in c7a93a5

2016-09-21 14:48 UTC, frank0631 commented on gocd/gocd_test.go
> +// //Test require a pipeline to have a history
better comments in f9acaa6

2016-09-21 14:55 UTC, frank0631 commented on rhobot.go
> +		f, createErr := os.Create(artifactSavePath)
separated in e4fcb0d

2016-09-21 14:55 UTC, frank0631 commented on rhobot.go
> +				if c.String(pipelineRunFlag.GetName()) != "" {
changed in b0b38d9

2016-09-21 14:55 UTC, frank0631 commented on rhobot.go
> +		Usage: "which run of the stage history",
changed in 7168cd3

2016-09-21 15:16 UTC, tanderegg approved these changes

2016-09-21 15:23 UTC, merged